title: CPR (SSN)                                                                              <script async type="text/javascript" src="/cpr/incl.js"></script>
description: Checking danish CPR-numbers (Personal identification number in Denmark)
