title: CPR <div align="right"><a href=".." title="Up"><kbd>&#x2303;</kbd></a><a href="/" title="Home"><kbd>&#x1F3E0;</kbd></a></div>
description: Checking danish CPR-numbers (Personal identification number in Denmark)
