title: cpr                 <script async type="text/javascript">var REPO="cpr";var DESC="Checking danish CPR-numbers";</script><script async type="text/javascript" src="/topmenu.js"></script>
description: Checking danish CPR-numbers
